## https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3
version: '3'

services:
  database:
    image: 'mongo'
    container_name: "eyespy-db-container"
    environment:
      - MONGO_INITDB_DATABASE=${PROJ_MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${PROJ_MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PROJ_MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db/init-mongo.js:/docker-entry-point-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    ports: 
      - '27017-27019:27017-27019'
